Lesson5
KonstantinLeineveber/TMS_110121 pull request #1
Opened 2021-01-30 13:58 UTC by KonstantinLeineveber

2021-02-01 13:07 UTC, NataliaKrolikova approved these changes
Внести изменения, учитывая комментарии.

2021-02-01 13:07 UTC, NataliaKrolikova commented on lesson5/src/metod/zad11.java
> +            System.out.println("n - Пpocтoe число");
Есди ты хотел здесь букву оставить то ок, если цифру, то не правильно прописал n.

2021-02-01 13:07 UTC, NataliaKrolikova commented on lesson5/src/metod/zad13.java
> +            System.out.println(array[0]);
Число выводится верное, но много раз.

2021-02-01 13:07 UTC, NataliaKrolikova commented on lesson5/src/metod/zad14.java
> +                indexMax = start + 1;
Здесь надо убрать + 1

2021-02-01 13:07 UTC, NataliaKrolikova commented on lesson5/src/metod/zad14.java
> +                indexMin = start + 1;
Здесь тоже надо убрать.

2021-02-01 13:07 UTC, NataliaKrolikova commented on lesson5/src/metod/zad14.java
> +        System.out.println("Максимальное значение в данном массиве = " + min + " и номер его  = " + indexMin);
Номер массива считается с 0. У тебя получается при выводе что номер считается от 1. Уберешь единицы выше и все правильно получится

2021-02-01 13:07 UTC, NataliaKrolikova commented on lesson5/src/other/hw1.java
> +        System.out.println(summ);
Здесь double правильней использовать на мой взгляд. В конце привести к int. Киллометров больше набегает.

2021-02-01 13:07 UTC, NataliaKrolikova commented on lesson5/src/other/hw3.java
> +}
Здесь не сумма получилась, а ты нашел последнее число и то с ошибкой. Выводит число 2048*2=4096. У тебя 4095. А надо сумма высчитать этих чисел.

2021-02-01 13:07 UTC, NataliaKrolikova commented on lesson5/src/other/hw3.java
> +}
А может не сумму. Не понятно что надо вычислить. В любом случае не верно, даже если надо вычислить следующее число.

2021-02-01 13:07 UTC, NataliaKrolikova commented on lesson5/src/other/hw6.java
> +        for (int i = 0; i <= 100; i += 2) {
Тут i должно быть равно 1, иначе на экран выводятся числа начиная с 0.

2021-02-01 14:38 UTC, KonstantinLeineveber commented on lesson5/src/metod/zad11.java
> +            System.out.println("n - Пpocтoe число");
Я и планировал букву

2021-02-01 14:42 UTC, KonstantinLeineveber commented on lesson5/src/metod/zad14.java
> +                indexMax = start + 1;
Я выводил номер не индекса, а его порядковый номер в последовательности, потому +1

2021-02-01 14:42 UTC, KonstantinLeineveber commented on lesson5/src/metod/zad14.java
> +                indexMin = start + 1;
Тоже самое, что и выше

2021-02-01 14:43 UTC, KonstantinLeineveber commented on lesson5/src/metod/zad14.java
> +        System.out.println("Максимальное значение в данном массиве = " + min + " и номер его  = " + indexMin);
Тоже самое, что и выше

2021-02-01 14:46 UTC, KonstantinLeineveber commented on lesson5/src/other/hw1.java
> +        System.out.println(summ);
Я думал через double делать, но из-за того, что java  неправильно ее считает, решил округлить

2021-02-01 14:54 UTC, KonstantinLeineveber commented on lesson5/src/other/hw3.java
> +}
В задании написано считать с единицы, я через дебаг несколько раз прогонял, все правильно вычисляет. Ради интереса пересчитал на калькуляторе - все выходит правильно.

2021-02-01 14:58 UTC, KonstantinLeineveber commented on lesson5/src/other/hw6.java
> +        for (int i = 0; i <= 100; i += 2) {
Согласно википедии 0 - это четное число)

2021-02-01 14:59 UTC, KonstantinLeineveber commented on lesson5/src/metod/zad13.java
> +            System.out.println(array[0]);
Спасибо. Подправил.

2021-02-01 15:26 UTC, KonstantinLeineveber reviewed
исправлена hw1, а не 14 задача

2021-02-01 16:02 UTC, NataliaKrolikova commented on lesson5/src/other/hw3.java
> +}
Да, это я неправильно условие задачи поняла.

2021-02-01 16:03 UTC, NataliaKrolikova commented on lesson5/src/other/hw6.java
> +        for (int i = 0; i <= 100; i += 2) {
А условие же вывести четные от 2)))

2021-02-01 19:39 UTC, KonstantinLeineveber commented on lesson5/src/other/hw6.java
> +        for (int i = 0; i <= 100; i += 2) {
точно, спасибо, исправил

2021-02-09 06:18 UTC, aimiebell commented on lesson5/src/metod/zad10.java
> +public class zad10 {
I detect that this code is problematic. According to the [Bad practice (BAD_PRACTICE)](https://spotbugs.readthedocs.io/en/stable/bugDescriptions.html#bad-practice-bad-practice), [Nm: Class names should start with an upper case letter (NM_CLASS_NAMING_CONVENTION)](https://spotbugs.readthedocs.io/en/stable/bugDescriptions.html#nm-class-names-should-start-with-an-upper-case-letter-nm-class-naming-convention).
Class names should be nouns, in mixed case with the first letter of each internal word capitalized. Try to keep your class names simple and descriptive. Use whole words-avoid acronyms and abbreviations (unless the abbreviation is much more widely used than the long form, such as URL or HTML).

2021-02-09 06:18 UTC, aimiebell commented on lesson5/src/metod/zad11.java
> +public class zad11 {
I detect that this code is problematic. According to the [Bad practice (BAD_PRACTICE)](https://spotbugs.readthedocs.io/en/stable/bugDescriptions.html#bad-practice-bad-practice), [Nm: Class names should start with an upper case letter (NM_CLASS_NAMING_CONVENTION)](https://spotbugs.readthedocs.io/en/stable/bugDescriptions.html#nm-class-names-should-start-with-an-upper-case-letter-nm-class-naming-convention).
Class names should be nouns, in mixed case with the first letter of each internal word capitalized. Try to keep your class names simple and descriptive. Use whole words-avoid acronyms and abbreviations (unless the abbreviation is much more widely used than the long form, such as URL or HTML).

2021-02-09 06:18 UTC, aimiebell commented on lesson5/src/metod/zad12.java
> +public class zad12 {
I detect that this code is problematic. According to the [Bad practice (BAD_PRACTICE)](https://spotbugs.readthedocs.io/en/stable/bugDescriptions.html#bad-practice-bad-practice), [Nm: Class names should start with an upper case letter (NM_CLASS_NAMING_CONVENTION)](https://spotbugs.readthedocs.io/en/stable/bugDescriptions.html#nm-class-names-should-start-with-an-upper-case-letter-nm-class-naming-convention).
Class names should be nouns, in mixed case with the first letter of each internal word capitalized. Try to keep your class names simple and descriptive. Use whole words-avoid acronyms and abbreviations (unless the abbreviation is much more widely used than the long form, such as URL or HTML).

2021-02-09 06:18 UTC, aimiebell commented on lesson5/src/metod/zad13.java
> +public class zad13 {
I detect that this code is problematic. According to the [Bad practice (BAD_PRACTICE)](https://spotbugs.readthedocs.io/en/stable/bugDescriptions.html#bad-practice-bad-practice), [Nm: Class names should start with an upper case letter (NM_CLASS_NAMING_CONVENTION)](https://spotbugs.readthedocs.io/en/stable/bugDescriptions.html#nm-class-names-should-start-with-an-upper-case-letter-nm-class-naming-convention).
Class names should be nouns, in mixed case with the first letter of each internal word capitalized. Try to keep your class names simple and descriptive. Use whole words-avoid acronyms and abbreviations (unless the abbreviation is much more widely used than the long form, such as URL or HTML).

2021-02-09 06:18 UTC, aimiebell commented on lesson5/src/metod/zad14.java
> +public class zad14 {
I detect that this code is problematic. According to the [Bad practice (BAD_PRACTICE)](https://spotbugs.readthedocs.io/en/stable/bugDescriptions.html#bad-practice-bad-practice), [Nm: Class names should start with an upper case letter (NM_CLASS_NAMING_CONVENTION)](https://spotbugs.readthedocs.io/en/stable/bugDescriptions.html#nm-class-names-should-start-with-an-upper-case-letter-nm-class-naming-convention).
Class names should be nouns, in mixed case with the first letter of each internal word capitalized. Try to keep your class names simple and descriptive. Use whole words-avoid acronyms and abbreviations (unless the abbreviation is much more widely used than the long form, such as URL or HTML).

2021-02-09 06:18 UTC, aimiebell commented on lesson5/src/metod/zad15.java
> +public class zad15 {
I detect that this code is problematic. According to the [Bad practice (BAD_PRACTICE)](https://spotbugs.readthedocs.io/en/stable/bugDescriptions.html#bad-practice-bad-practice), [Nm: Class names should start with an upper case letter (NM_CLASS_NAMING_CONVENTION)](https://spotbugs.readthedocs.io/en/stable/bugDescriptions.html#nm-class-names-should-start-with-an-upper-case-letter-nm-class-naming-convention).
Class names should be nouns, in mixed case with the first letter of each internal word capitalized. Try to keep your class names simple and descriptive. Use whole words-avoid acronyms and abbreviations (unless the abbreviation is much more widely used than the long form, such as URL or HTML).

2021-02-09 06:18 UTC, aimiebell commented on lesson5/src/metod/zad16.java
> +public class zad16 {
I detect that this code is problematic. According to the [Bad practice (BAD_PRACTICE)](https://spotbugs.readthedocs.io/en/stable/bugDescriptions.html#bad-practice-bad-practice), [Nm: Class names should start with an upper case letter (NM_CLASS_NAMING_CONVENTION)](https://spotbugs.readthedocs.io/en/stable/bugDescriptions.html#nm-class-names-should-start-with-an-upper-case-letter-nm-class-naming-convention).
Class names should be nouns, in mixed case with the first letter of each internal word capitalized. Try to keep your class names simple and descriptive. Use whole words-avoid acronyms and abbreviations (unless the abbreviation is much more widely used than the long form, such as URL or HTML).

2021-02-09 06:18 UTC, aimiebell commented on lesson5/src/metod/zad17.java
> +public class zad17 {
I detect that this code is problematic. According to the [Bad practice (BAD_PRACTICE)](https://spotbugs.readthedocs.io/en/stable/bugDescriptions.html#bad-practice-bad-practice), [Nm: Class names should start with an upper case letter (NM_CLASS_NAMING_CONVENTION)](https://spotbugs.readthedocs.io/en/stable/bugDescriptions.html#nm-class-names-should-start-with-an-upper-case-letter-nm-class-naming-convention).
Class names should be nouns, in mixed case with the first letter of each internal word capitalized. Try to keep your class names simple and descriptive. Use whole words-avoid acronyms and abbreviations (unless the abbreviation is much more widely used than the long form, such as URL or HTML).

2021-02-09 06:18 UTC, aimiebell commented on lesson5/src/metod/zad9.java
> +public class zad9 {
I detect that this code is problematic. According to the [Bad practice (BAD_PRACTICE)](https://spotbugs.readthedocs.io/en/stable/bugDescriptions.html#bad-practice-bad-practice), [Nm: Class names should start with an upper case letter (NM_CLASS_NAMING_CONVENTION)](https://spotbugs.readthedocs.io/en/stable/bugDescriptions.html#nm-class-names-should-start-with-an-upper-case-letter-nm-class-naming-convention).
Class names should be nouns, in mixed case with the first letter of each internal word capitalized. Try to keep your class names simple and descriptive. Use whole words-avoid acronyms and abbreviations (unless the abbreviation is much more widely used than the long form, such as URL or HTML).

2021-02-09 06:18 UTC, aimiebell commented on lesson5/src/other/hw1.java
> +public class hw1 {
I detect that this code is problematic. According to the [Bad practice (BAD_PRACTICE)](https://spotbugs.readthedocs.io/en/stable/bugDescriptions.html#bad-practice-bad-practice), [Nm: Class names should start with an upper case letter (NM_CLASS_NAMING_CONVENTION)](https://spotbugs.readthedocs.io/en/stable/bugDescriptions.html#nm-class-names-should-start-with-an-upper-case-letter-nm-class-naming-convention).
Class names should be nouns, in mixed case with the first letter of each internal word capitalized. Try to keep your class names simple and descriptive. Use whole words-avoid acronyms and abbreviations (unless the abbreviation is much more widely used than the long form, such as URL or HTML).

2021-02-09 06:18 UTC, aimiebell commented on lesson5/src/other/hw2.java
> +public class hw2 {
I detect that this code is problematic. According to the [Bad practice (BAD_PRACTICE)](https://spotbugs.readthedocs.io/en/stable/bugDescriptions.html#bad-practice-bad-practice), [Nm: Class names should start with an upper case letter (NM_CLASS_NAMING_CONVENTION)](https://spotbugs.readthedocs.io/en/stable/bugDescriptions.html#nm-class-names-should-start-with-an-upper-case-letter-nm-class-naming-convention).
Class names should be nouns, in mixed case with the first letter of each internal word capitalized. Try to keep your class names simple and descriptive. Use whole words-avoid acronyms and abbreviations (unless the abbreviation is much more widely used than the long form, such as URL or HTML).

2021-02-09 06:18 UTC, aimiebell commented on lesson5/src/other/hw3.java
> +public class hw3 {
I detect that this code is problematic. According to the [Bad practice (BAD_PRACTICE)](https://spotbugs.readthedocs.io/en/stable/bugDescriptions.html#bad-practice-bad-practice), [Nm: Class names should start with an upper case letter (NM_CLASS_NAMING_CONVENTION)](https://spotbugs.readthedocs.io/en/stable/bugDescriptions.html#nm-class-names-should-start-with-an-upper-case-letter-nm-class-naming-convention).
Class names should be nouns, in mixed case with the first letter of each internal word capitalized. Try to keep your class names simple and descriptive. Use whole words-avoid acronyms and abbreviations (unless the abbreviation is much more widely used than the long form, such as URL or HTML).

2021-02-09 06:18 UTC, aimiebell commented on lesson5/src/other/hw4.java
> +public class hw4 {
I detect that this code is problematic. According to the [Bad practice (BAD_PRACTICE)](https://spotbugs.readthedocs.io/en/stable/bugDescriptions.html#bad-practice-bad-practice), [Nm: Class names should start with an upper case letter (NM_CLASS_NAMING_CONVENTION)](https://spotbugs.readthedocs.io/en/stable/bugDescriptions.html#nm-class-names-should-start-with-an-upper-case-letter-nm-class-naming-convention).
Class names should be nouns, in mixed case with the first letter of each internal word capitalized. Try to keep your class names simple and descriptive. Use whole words-avoid acronyms and abbreviations (unless the abbreviation is much more widely used than the long form, such as URL or HTML).

2021-02-09 06:18 UTC, aimiebell commented on lesson5/src/other/hw5.java
> +public class hw5 {
I detect that this code is problematic. According to the [Bad practice (BAD_PRACTICE)](https://spotbugs.readthedocs.io/en/stable/bugDescriptions.html#bad-practice-bad-practice), [Nm: Class names should start with an upper case letter (NM_CLASS_NAMING_CONVENTION)](https://spotbugs.readthedocs.io/en/stable/bugDescriptions.html#nm-class-names-should-start-with-an-upper-case-letter-nm-class-naming-convention).
Class names should be nouns, in mixed case with the first letter of each internal word capitalized. Try to keep your class names simple and descriptive. Use whole words-avoid acronyms and abbreviations (unless the abbreviation is much more widely used than the long form, such as URL or HTML).

2021-02-09 06:18 UTC, aimiebell commented on lesson5/src/other/hw6.java
> +public class hw6 {
I detect that this code is problematic. According to the [Bad practice (BAD_PRACTICE)](https://spotbugs.readthedocs.io/en/stable/bugDescriptions.html#bad-practice-bad-practice), [Nm: Class names should start with an upper case letter (NM_CLASS_NAMING_CONVENTION)](https://spotbugs.readthedocs.io/en/stable/bugDescriptions.html#nm-class-names-should-start-with-an-upper-case-letter-nm-class-naming-convention).
Class names should be nouns, in mixed case with the first letter of each internal word capitalized. Try to keep your class names simple and descriptive. Use whole words-avoid acronyms and abbreviations (unless the abbreviation is much more widely used than the long form, such as URL or HTML).

2021-02-09 06:18 UTC, aimiebell commented on lesson5/src/other/hw7.java
> +public class hw7 {
I detect that this code is problematic. According to the [Bad practice (BAD_PRACTICE)](https://spotbugs.readthedocs.io/en/stable/bugDescriptions.html#bad-practice-bad-practice), [Nm: Class names should start with an upper case letter (NM_CLASS_NAMING_CONVENTION)](https://spotbugs.readthedocs.io/en/stable/bugDescriptions.html#nm-class-names-should-start-with-an-upper-case-letter-nm-class-naming-convention).
Class names should be nouns, in mixed case with the first letter of each internal word capitalized. Try to keep your class names simple and descriptive. Use whole words-avoid acronyms and abbreviations (unless the abbreviation is much more widely used than the long form, such as URL or HTML).

2021-02-13 14:07 UTC, RomanKashenok requested changes

2021-02-13 14:07 UTC, RomanKashenok commented on lesson5/src/metod/zad13.java
> +        System.out.println(array[0]);
жестко конечно сделать столько проходов, что бы найти число, хотя это можно было и за один проход сделать

2021-02-13 14:07 UTC, RomanKashenok commented on lesson5/src/metod/zad14.java
> +                indexMax = start + 1;
ну это вообще странно ) говоря про массивы имеют в виду индекс. Но ок :)

2021-02-13 14:07 UTC, RomanKashenok commented on lesson5/src/metod/zad16.java
> +        System.out.print("сумма элементов массива, расположенных между минимальным и максимальным значениями = ");
Если честно вообще не понимаю какая тут логика. Ты высчитал сумму всех элементов массива а потом отнял максимальное и минимальное?
А ели массив такой: 1,2,3,100,50,40,30,20. По идее мне нужно по итогу получить 106, а получу я 145

2021-02-13 14:07 UTC, RomanKashenok commented on lesson5/src/metod/zad17.java
> +        char[][] arr2 = new char[5][5];
В условии речь идет про один массив. убери второй

2021-02-13 14:07 UTC, RomanKashenok commented on lesson5/src/other/hw2.java
> +            } else ameba *= 2;
1. форматирование. 
2. Не используемые блоки if - зло. Убери отовсюду такие условия (у тебя их в задачах несколько)

2021-02-13 14:07 UTC, RomanKashenok commented on lesson5/src/other/hw3.java
> +//        Вычислить: 1+2+4+8+...+2564) Составьте программу, вычисляющую A*B, не пользуясь операцией умножения.
вообще тут последовательность до 256, а 4) - это 4я задача

2021-02-13 14:07 UTC, RomanKashenok commented on lesson5/src/other/hw4.java
> +        for (int i = 0; i < b; i++) {
странно только что ты выбрал 11 итераций сложения восьмерки, вместо восьми итераций сложения 11ти

2021-06-02 17:10 UTC, KonstantinLeineveber commented on lesson5/src/metod/zad13.java
> +        System.out.println(array[0]);
исправил

2021-06-07 17:56 UTC, KonstantinLeineveber commented on lesson5/src/metod/zad13.java
> +        System.out.println(array[0]);
Исправил

2021-06-07 17:57 UTC, KonstantinLeineveber commented on lesson5/src/metod/zad17.java
> +        char[][] arr2 = new char[5][5];
Исправил

2021-06-07 17:57 UTC, KonstantinLeineveber commented on lesson5/src/other/hw3.java
> +//        Вычислить: 1+2+4+8+...+2564) Составьте программу, вычисляющую A*B, не пользуясь операцией умножения.
Исправил

2021-06-07 17:57 UTC, KonstantinLeineveber commented on lesson5/src/other/hw4.java
> +        for (int i = 0; i < b; i++) {
Исправил

2021-11-29 12:24 UTC, merged