lesson 17
KonstantinLeineveber/TMS_110121 pull request #10
Opened 2021-04-04 15:24 UTC by KonstantinLeineveber

2021-04-06 10:00 UTC, RomanKashenok requested changes

2021-04-06 10:00 UTC, RomanKashenok commented on lesson17/src/exchanger/Exchanger.java
> +                lock.lock();
не совсем правильно, а точнее совсем не правильно, делать много потоков для одного единственного продавца-покупателя. Скорее каждый продавец-покупатель должен быть отдельным потоком. А еще лок делать на каком-нибудь объекте CurrencyExchangeOffice

2021-04-06 10:00 UTC, RomanKashenok commented on lesson17/src/exchanger/Buyer.java
> +    public void CurrencyExchange() {
методы с маленькой буквы

2021-04-06 10:00 UTC, RomanKashenok commented on lesson17/src/library/Books.java
> +public class Books {
class Book, не Books

2021-04-06 10:00 UTC, RomanKashenok commented on lesson17/src/library/Reading_Room.java
> +public class Reading_Room {
ReadingRoom

2021-04-06 10:00 UTC, RomanKashenok commented on lesson17/src/library/Reading_Room.java
> +        GetBooks.getAllBooks();
присвой результат чему-то (ты в 28й строке еще раз парсишь весь XML)

2021-06-16 16:09 UTC, KonstantinLeineveber commented on lesson17/src/exchanger/Buyer.java
> +    public void CurrencyExchange() {
Исправил

2021-06-16 16:09 UTC, KonstantinLeineveber commented on lesson17/src/library/Reading_Room.java
> +public class Reading_Room {
Исправил

2021-06-16 16:10 UTC, KonstantinLeineveber commented on lesson17/src/library/Books.java
> +public class Books {
Исправил

2021-06-16 16:26 UTC, KonstantinLeineveber commented on lesson17/src/library/Reading_Room.java
> +        GetBooks.getAllBooks();
Исправил

2021-06-16 17:00 UTC, KonstantinLeineveber commented on lesson17/src/exchanger/Exchanger.java
> +                lock.lock();
Исправил

2021-11-29 13:31 UTC, merged