Крестики-нолики
KonstantinLeineveber/TMS_110121 pull request #2
Opened 2021-02-06 12:11 UTC by KonstantinLeineveber

2021-02-07 14:38 UTC, RomanKashenok requested changes
Вы играете крестиками, вводить только заглавную букву Х
Введите номер строки, где будете вводить крестик
3
Введите номер столбца, где будете вводить крестик
3
null       null       null       
null       null       null       
null       null       X       

O       null       null       
null       null       null       
null       null       X       
Введите номер строки, где будете вводить крестик
2
Введите номер столбца, где будете вводить крестик
2
O       null       null       
null       X       null       
null       null       X       

O       null       null       
null       X       O       
null       null       X       
Введите номер строки, где будете вводить крестик
1
Введите номер столбца, где будете вводить крестик
2
Вы победили!

Process finished with exit code 0

2021-02-07 15:42 UTC, KonstantinLeineveber commented
Исправил

2021-02-12 09:20 UTC, RomanKashenok reviewed
- при вводе числа не от 1 до 3 игра заканчивается (решается циклом while с правильным условием)
- при попадании в занятую ячейку игра заканчивается

2021-02-12 09:20 UTC, RomanKashenok commented on KrestNol/src/KrestNol.java
> +        Scanner sto = new Scanner(System.in);
Зачем два потока ввода?

2021-02-12 18:32 UTC, KonstantinLeineveber commented on KrestNol/src/KrestNol.java
> +        Scanner sto = new Scanner(System.in);
Одно для ввода номера строки, другое для ввода столбца

2021-02-13 15:33 UTC, RomanKashenok approved these changes

2021-02-13 15:33 UTC, merged