lesson8
KonstantinLeineveber/TMS_110121 pull request #3
Opened 2021-02-06 17:51 UTC by KonstantinLeineveber

2021-02-07 15:22 UTC, RomanKashenok requested changes

2021-02-07 15:22 UTC, RomanKashenok commented on lessom8/src/string/zad23.java
> +        Pattern pattern1 = Pattern.compile("-*<p id=”p[0-9]*”>");
paragraph tag could contain much more attributs than only id (it could be style, class, aligh and ctr.). You need to find universal solution for that

2021-02-07 15:22 UTC, RomanKashenok commented on lessom8/src/string/zad18.java
> +            symbol = str.charAt(i);
It's really complicated logic.
I'll offer you few solutions more: 
1. get str.toCharArray() and iterate over characters (not a best solution)
2. Use PAttern/Matcher (better soltion)

2021-02-07 15:22 UTC, RomanKashenok commented on lessom8/src/string/zad19.java
> +            symbol = str.charAt(i);
it's wrong solution in general - to separate words with inly spaces. Try to check your logic with next string for example: "        String str = "this,string   contains:six separated, words";"
And use Pattern - Matcher here (or StringTokenizer)

2021-02-07 15:22 UTC, RomanKashenok commented on lessom8/src/string/zad20.java
> +            if (symbol == ',' || symbol == '.' || symbol == '-' || symbol == ':' || symbol == ';'
the same comment as in previous task

2021-02-09 06:18 UTC, aimiebell commented on lessom8/src/string/zad18.java
> +public class zad18 {
I detect that this code is problematic. According to the [Bad practice (BAD_PRACTICE)](https://spotbugs.readthedocs.io/en/stable/bugDescriptions.html#bad-practice-bad-practice), [Nm: Class names should start with an upper case letter (NM_CLASS_NAMING_CONVENTION)](https://spotbugs.readthedocs.io/en/stable/bugDescriptions.html#nm-class-names-should-start-with-an-upper-case-letter-nm-class-naming-convention).
Class names should be nouns, in mixed case with the first letter of each internal word capitalized. Try to keep your class names simple and descriptive. Use whole words-avoid acronyms and abbreviations (unless the abbreviation is much more widely used than the long form, such as URL or HTML).

2021-02-09 06:18 UTC, aimiebell commented on lessom8/src/string/zad19.java
> +public class zad19 {
I detect that this code is problematic. According to the [Bad practice (BAD_PRACTICE)](https://spotbugs.readthedocs.io/en/stable/bugDescriptions.html#bad-practice-bad-practice), [Nm: Class names should start with an upper case letter (NM_CLASS_NAMING_CONVENTION)](https://spotbugs.readthedocs.io/en/stable/bugDescriptions.html#nm-class-names-should-start-with-an-upper-case-letter-nm-class-naming-convention).
Class names should be nouns, in mixed case with the first letter of each internal word capitalized. Try to keep your class names simple and descriptive. Use whole words-avoid acronyms and abbreviations (unless the abbreviation is much more widely used than the long form, such as URL or HTML).

2021-02-09 06:18 UTC, aimiebell commented on lessom8/src/string/zad20.java
> +public class zad20 {
I detect that this code is problematic. According to the [Bad practice (BAD_PRACTICE)](https://spotbugs.readthedocs.io/en/stable/bugDescriptions.html#bad-practice-bad-practice), [Nm: Class names should start with an upper case letter (NM_CLASS_NAMING_CONVENTION)](https://spotbugs.readthedocs.io/en/stable/bugDescriptions.html#nm-class-names-should-start-with-an-upper-case-letter-nm-class-naming-convention).
Class names should be nouns, in mixed case with the first letter of each internal word capitalized. Try to keep your class names simple and descriptive. Use whole words-avoid acronyms and abbreviations (unless the abbreviation is much more widely used than the long form, such as URL or HTML).

2021-02-09 06:18 UTC, aimiebell commented on lessom8/src/string/zad21.java
> +public class zad21 {
I detect that this code is problematic. According to the [Bad practice (BAD_PRACTICE)](https://spotbugs.readthedocs.io/en/stable/bugDescriptions.html#bad-practice-bad-practice), [Nm: Class names should start with an upper case letter (NM_CLASS_NAMING_CONVENTION)](https://spotbugs.readthedocs.io/en/stable/bugDescriptions.html#nm-class-names-should-start-with-an-upper-case-letter-nm-class-naming-convention).
Class names should be nouns, in mixed case with the first letter of each internal word capitalized. Try to keep your class names simple and descriptive. Use whole words-avoid acronyms and abbreviations (unless the abbreviation is much more widely used than the long form, such as URL or HTML).

2021-02-09 06:18 UTC, aimiebell commented on lessom8/src/string/zad22.java
> +public class zad22 {
I detect that this code is problematic. According to the [Bad practice (BAD_PRACTICE)](https://spotbugs.readthedocs.io/en/stable/bugDescriptions.html#bad-practice-bad-practice), [Nm: Class names should start with an upper case letter (NM_CLASS_NAMING_CONVENTION)](https://spotbugs.readthedocs.io/en/stable/bugDescriptions.html#nm-class-names-should-start-with-an-upper-case-letter-nm-class-naming-convention).
Class names should be nouns, in mixed case with the first letter of each internal word capitalized. Try to keep your class names simple and descriptive. Use whole words-avoid acronyms and abbreviations (unless the abbreviation is much more widely used than the long form, such as URL or HTML).

2021-02-09 06:18 UTC, aimiebell commented on lessom8/src/string/zad23.java
> +public class zad23 {
I detect that this code is problematic. According to the [Bad practice (BAD_PRACTICE)](https://spotbugs.readthedocs.io/en/stable/bugDescriptions.html#bad-practice-bad-practice), [Nm: Class names should start with an upper case letter (NM_CLASS_NAMING_CONVENTION)](https://spotbugs.readthedocs.io/en/stable/bugDescriptions.html#nm-class-names-should-start-with-an-upper-case-letter-nm-class-naming-convention).
Class names should be nouns, in mixed case with the first letter of each internal word capitalized. Try to keep your class names simple and descriptive. Use whole words-avoid acronyms and abbreviations (unless the abbreviation is much more widely used than the long form, such as URL or HTML).

2021-02-11 18:58 UTC, KonstantinLeineveber commented on lessom8/src/string/zad23.java
> +        Pattern pattern1 = Pattern.compile("-*<p id=”p[0-9]*”>");
исправил

2021-02-11 18:58 UTC, KonstantinLeineveber commented on lessom8/src/string/zad18.java
> +            symbol = str.charAt(i);
исправил

2021-02-11 18:58 UTC, KonstantinLeineveber commented on lessom8/src/string/zad20.java
> +            if (symbol == ',' || symbol == '.' || symbol == '-' || symbol == ':' || symbol == ';'
исправил

2021-02-11 18:58 UTC, KonstantinLeineveber commented on lessom8/src/string/zad19.java
> +            symbol = str.charAt(i);
исправил

2021-02-13 15:09 UTC, merged