lesson10
KonstantinLeineveber/TMS_110121 pull request #4
Opened 2021-03-03 18:19 UTC by KonstantinLeineveber

2021-03-09 20:30 UTC, RomanKashenok requested changes
Надо бы переделать всё

2021-03-09 20:30 UTC, RomanKashenok commented on lesson10/src/by/teachmeskills/human/Human.java
> +    private Kosuha kosuha;
переменные объявляй по типу (по интерфейсу)

2021-03-09 20:30 UTC, RomanKashenok commented on lesson10/src/by/teachmeskills/human/Human2.java
> +public class Human2 implements PreHuman {
уже есть реализация - убирай

2021-03-09 20:30 UTC, RomanKashenok commented on lesson10/src/by/teachmeskills/human/Human3.java
> +public class Human3 implements PreHuman {
уже есть реализация - убирай

2021-03-09 20:30 UTC, RomanKashenok commented on lesson10/src/by/teachmeskills/human/Run.java
> +        Human human = new Human(new Kosuha(), new Bruki(), new Botinki());
создавай по типу (PreHuman)

2021-03-09 20:30 UTC, RomanKashenok commented on lesson10/src/by/teachmeskills/human/Run.java
> +        Human human = new Human(new Kosuha(), new Bruki(), new Botinki());
Всю одежду создавай тоже по типу (Kurtka, Obuv...)

2021-03-09 20:30 UTC, RomanKashenok commented on lesson10/src/by/teachmeskills/kosmodrom/Shattl.java
> +class Shattl extends Kosmodrom implements Istart {
Шатл расширяет космодром?
убирай космодром отсюда

2021-03-09 20:30 UTC, RomanKashenok commented on lesson10/src/by/teachmeskills/kosmodrom/SpaceRanger.java
> +class SpaceRanger extends Kosmodrom implements Istart {
тоже самое

2021-03-09 20:30 UTC, RomanKashenok commented on lesson10/src/by/teachmeskills/kosmodrom/SpaceX.java
> +class SpaceX extends Kosmodrom implements Istart {
тоже самое

2021-03-09 20:30 UTC, RomanKashenok commented on lesson10/src/by/teachmeskills/robot/Robot1.java
> +    private SonyHead head;
поля создавай по типам

2021-03-09 20:30 UTC, RomanKashenok commented on lesson10/src/by/teachmeskills/robot/Robot2.java
> +    private SamsungHead head;
по типам (как в предыдущем)

2021-03-09 20:30 UTC, RomanKashenok commented on lesson10/src/by/teachmeskills/robot/Robot3.java
> +    private ToshibaHead head;
по типам (как в предыдущем)

2021-03-09 20:30 UTC, RomanKashenok commented on lesson10/src/metodichka/zad1/Graghdanskij.java
> +        StringBuilder s = new StringBuilder();
Это что вообще за метод и что он по итогу делает?

2021-03-09 20:30 UTC, RomanKashenok commented on lesson10/src/metodichka/zad1/Gruzovoj.java
> +    public StringBuilder gruz(int mochnost, int maxSkor, int mass, String marka,
тоже самое

2021-03-09 20:30 UTC, RomanKashenok commented on lesson10/src/metodichka/zad1/Legkovoj.java
> +    public StringBuilder legk(int mochnost, int maxSkor, int mass, String marka,
тоже самое

2021-03-09 20:30 UTC, RomanKashenok commented on lesson10/src/zad24/runner.java
> +class runner {
классы с большой буквы

2021-03-09 20:30 UTC, RomanKashenok commented on lesson10/src/zad24/runner.java
> +        vremya a = new vremya(1163, 32360, 165);
с большой буквы

2021-03-09 20:30 UTC, RomanKashenok commented on lesson10/src/zad24/vremya.java
> +        System.out.println("Количество минут и секунд в указанном числе = " + m + " и " + sec);
убирай выводы из конструктора

2021-03-09 20:30 UTC, RomanKashenok commented on lesson10/src/zad24/vremya.java
> +    private int summS;
сумма интов может выйти за пределы инта - делай лонг

2021-03-09 20:30 UTC, RomanKashenok commented on lesson10/src/zad25/bankomat.java
> +            System.out.println("Операция " + snyal);
а где вычисление остатка в банкомате?

2021-03-09 20:30 UTC, RomanKashenok commented on lesson10/src/zad26/bit_tech.java
> +public class bit_tech {
с большой буквы, и кэмэл кейсом

2021-03-09 20:30 UTC, RomanKashenok commented on lesson10/src/zad26/bit_tech.java
> +    private boolean razetka = false;
что такое разетка?

2021-03-09 20:30 UTC, RomanKashenok commented on lesson10/src/zad26/krupnaya_bit_tech.java
> +class krupnaya_bit_tech extends bit_tech {
называй классы правильно

2021-03-09 20:30 UTC, RomanKashenok commented on lesson10/src/zad26/krupnaya_bit_tech.java
> +    public int dlina, shirina, visota, ves;
private. Геттеры и Сеттеры

2021-03-09 20:30 UTC, RomanKashenok commented on lesson10/src/zad26/stiralka.java
> +//    @Override        С этим нужна помощь!!!
убирай комментарии

2021-03-09 20:30 UTC, RomanKashenok commented on lesson10/src/zad26/stiralka.java
> +        return "Stiralnaya mashina{" +
Забирай часть данных из суперкласса, а не тащи все отсюда

2021-03-09 20:30 UTC, RomanKashenok commented on lesson10/src/zad27/kartochka.java
> +        System.out.println("Ваша банковская карта {" +
убирай вывод из конструктора

2021-03-09 20:30 UTC, RomanKashenok commented on lesson10/src/zad27/plastikovaya.java
> +public class plastikovaya extends bankovkaya {
если класс расширяет, то в нем что-то должно отличаться от класса-родителя

2021-06-15 12:36 UTC, KonstantinLeineveber commented on lesson10/src/by/teachmeskills/human/Human.java
> +    private Kosuha kosuha;
исправить

2021-06-15 12:36 UTC, KonstantinLeineveber commented on lesson10/src/by/teachmeskills/human/Human2.java
> +public class Human2 implements PreHuman {
исправить

2021-06-15 12:37 UTC, KonstantinLeineveber commented on lesson10/src/by/teachmeskills/human/Human3.java
> +public class Human3 implements PreHuman {
исправил

2021-06-15 12:37 UTC, KonstantinLeineveber commented on lesson10/src/by/teachmeskills/human/Run.java
> +        Human human = new Human(new Kosuha(), new Bruki(), new Botinki());
исправил

2021-06-15 12:37 UTC, KonstantinLeineveber commented on lesson10/src/by/teachmeskills/human/Run.java
> +        Human human = new Human(new Kosuha(), new Bruki(), new Botinki());
исправил

2021-06-15 13:28 UTC, KonstantinLeineveber commented on lesson10/src/by/teachmeskills/kosmodrom/Shattl.java
> +class Shattl extends Kosmodrom implements Istart {
исправил

2021-06-15 13:29 UTC, KonstantinLeineveber commented on lesson10/src/by/teachmeskills/kosmodrom/SpaceRanger.java
> +class SpaceRanger extends Kosmodrom implements Istart {
исправил

2021-06-15 13:29 UTC, KonstantinLeineveber commented on lesson10/src/by/teachmeskills/kosmodrom/SpaceX.java
> +class SpaceX extends Kosmodrom implements Istart {
исправил

2021-06-15 14:05 UTC, KonstantinLeineveber commented on lesson10/src/by/teachmeskills/robot/Robot1.java
> +    private SonyHead head;
убрал реализацию

2021-06-15 14:05 UTC, KonstantinLeineveber commented on lesson10/src/by/teachmeskills/robot/Robot2.java
> +    private SamsungHead head;
убрал реализацию

2021-06-15 14:05 UTC, KonstantinLeineveber commented on lesson10/src/by/teachmeskills/robot/Robot3.java
> +    private ToshibaHead head;
убрал реализацию

2021-06-15 14:24 UTC, KonstantinLeineveber commented on lesson10/src/metodichka/zad1/Graghdanskij.java
> +        StringBuilder s = new StringBuilder();
исправил

2021-06-15 14:40 UTC, KonstantinLeineveber commented on lesson10/src/metodichka/zad1/Gruzovoj.java
> +    public StringBuilder gruz(int mochnost, int maxSkor, int mass, String marka,
исправил

2021-06-15 14:40 UTC, KonstantinLeineveber commented on lesson10/src/metodichka/zad1/Legkovoj.java
> +    public StringBuilder legk(int mochnost, int maxSkor, int mass, String marka,
исправил

2021-06-15 14:43 UTC, KonstantinLeineveber commented on lesson10/src/zad24/runner.java
> +        vremya a = new vremya(1163, 32360, 165);
исправил

2021-06-15 14:44 UTC, KonstantinLeineveber commented on lesson10/src/zad24/runner.java
> +class runner {
исправил

2021-06-15 14:48 UTC, KonstantinLeineveber commented on lesson10/src/zad24/vremya.java
> +    private int summS;
исправил

2021-06-15 15:00 UTC, KonstantinLeineveber commented on lesson10/src/zad24/vremya.java
> +        System.out.println("Количество минут и секунд в указанном числе = " + m + " и " + sec);
исправил

2021-06-15 18:30 UTC, KonstantinLeineveber commented on lesson10/src/zad25/bankomat.java
> +            System.out.println("Операция " + snyal);
исправил

2021-06-15 18:34 UTC, KonstantinLeineveber commented on lesson10/src/zad26/bit_tech.java
> +public class bit_tech {
исправил

2021-06-15 18:35 UTC, KonstantinLeineveber commented on lesson10/src/zad26/bit_tech.java
> +    private boolean razetka = false;
включен ли прибор в розетку

2021-06-15 18:35 UTC, KonstantinLeineveber commented on lesson10/src/zad26/krupnaya_bit_tech.java
> +class krupnaya_bit_tech extends bit_tech {
исправил

2021-06-15 18:36 UTC, KonstantinLeineveber commented on lesson10/src/zad26/stiralka.java
> +//    @Override        С этим нужна помощь!!!
убрал

2021-06-15 18:41 UTC, KonstantinLeineveber commented on lesson10/src/zad26/krupnaya_bit_tech.java
> +    public int dlina, shirina, visota, ves;
исправил

2021-06-15 18:48 UTC, KonstantinLeineveber commented on lesson10/src/zad26/stiralka.java
> +        return "Stiralnaya mashina{" +
исправил

2021-06-15 18:51 UTC, KonstantinLeineveber commented on lesson10/src/zad27/plastikovaya.java
> +public class plastikovaya extends bankovkaya {
Они же отличаются

2021-06-15 18:54 UTC, KonstantinLeineveber commented on lesson10/src/zad27/kartochka.java
> +        System.out.println("Ваша банковская карта {" +
исправил

2021-11-29 13:30 UTC, merged