lesson15
KonstantinLeineveber/TMS_110121 pull request #7
Opened 2021-03-12 21:20 UTC by KonstantinLeineveber

2021-03-16 10:37 UTC, RomanKashenok requested changes

2021-03-16 10:37 UTC, RomanKashenok commented on lesson15/src/other/dopolnitelnoe_zadaniye1/dop1.java
> +        while ((a = br.read()) != -1) {
BufferedReader умеет читать построчно (redLine)

2021-03-16 10:37 UTC, RomanKashenok commented on lesson15/src/other/dopolnitelnoe_zadaniye1/dop1.java
> +        char[] reverse = new char[arrayList.size()];
StringBulder умеет переворачивать строки

2021-03-16 10:37 UTC, RomanKashenok commented on lesson15/src/other/dopolnitelnoe_zadaniye1/dop1.java
> +
я вообще не понял что тут происходит. ты зачем-то посимвольно вычитываешь файл в ArrayList, потом ты создаешь еще один массив с перевернутой инфой из этого листа, потом ты к тому, что есть в листе добавляешь эти перевернутые данные и потом все это пишешь в файл? 
я вот в условии вообще ничего такого не видел )

2021-03-16 10:37 UTC, RomanKashenok commented on lesson15/src/other/dopolnitelnoe_zadaniye2/TextFormater.java
> +    }
реально сильно сложно. StringBuilder.reverse() - вот и все

2021-03-16 10:37 UTC, RomanKashenok commented on lesson15/src/other/dopolnitelnoe_zadaniye2/main.java
> +            } else if (numWord(res) > 2 & numWord(res) < 6 & !palindrome(res)) {
ты дважды вычисляешь содержание полиндромов (вызываешь вон ну сложную логику дважды) и дважды считаешь количество слов в предложении. !palindrome(res) - это уже априори true

2021-03-16 10:37 UTC, RomanKashenok commented on lesson15/src/other/dopolnitelnoe_zadaniye3/dop3.java
> +        String[] str1 = str.split(" +");
вместо строк с 27 по эту можно было просто слова класть в список

2021-03-16 10:37 UTC, RomanKashenok commented on lesson15/src/other/dopolnitelnoe_zadaniye3/dop3.java
> +        for (int i = 0; i < str1.length; i++) {
Ты выбрал самую сложную и дорогую операцию из возможных, а можно было просто считать текст и по одному слову проверить на содержание нецензурных слов

2021-03-16 10:37 UTC, RomanKashenok commented on lesson15/src/zad35.java
> +public class zad35 {
классы с большой буквы

2021-06-16 13:52 UTC, KonstantinLeineveber commented on lesson15/src/other/dopolnitelnoe_zadaniye1/dop1.java
> +        while ((a = br.read()) != -1) {
исправил

2021-06-16 13:52 UTC, KonstantinLeineveber commented on lesson15/src/other/dopolnitelnoe_zadaniye1/dop1.java
> +        char[] reverse = new char[arrayList.size()];
исправил

2021-06-16 13:53 UTC, KonstantinLeineveber commented on lesson15/src/other/dopolnitelnoe_zadaniye1/dop1.java
> +
Я погуглил, что такое палидром. Палидромом может быть текст задом наперед. Потому решил, что требовалось перевернуть весь текст. Но все переделал.

2021-06-16 15:34 UTC, KonstantinLeineveber commented on lesson15/src/other/dopolnitelnoe_zadaniye2/TextFormater.java
> +    }
исправил

2021-06-16 15:34 UTC, KonstantinLeineveber commented on lesson15/src/other/dopolnitelnoe_zadaniye2/main.java
> +            } else if (numWord(res) > 2 & numWord(res) < 6 & !palindrome(res)) {
Понял и исправил

2021-06-16 15:34 UTC, KonstantinLeineveber commented on lesson15/src/zad35.java
> +public class zad35 {
исправил

2021-06-16 16:05 UTC, KonstantinLeineveber commented on lesson15/src/other/dopolnitelnoe_zadaniye3/dop3.java
> +        String[] str1 = str.split(" +");
исправил

2021-06-16 16:05 UTC, KonstantinLeineveber commented on lesson15/src/other/dopolnitelnoe_zadaniye3/dop3.java
> +        for (int i = 0; i < str1.length; i++) {
исправил

2021-11-29 13:30 UTC, merged