Lesson13
KonstantinLeineveber/TMS_110121 pull request #8
Opened 2021-03-12 21:20 UTC by KonstantinLeineveber

2021-03-16 10:44 UTC, RomanKashenok requested changes

2021-03-16 10:44 UTC, RomanKashenok commented on lesson13/src/zad29.java
> +public class zad29 {
с большой буквы

2021-03-16 10:44 UTC, RomanKashenok commented on lesson13/src/zad29.java
> +        score.removeIf(n -> n < 4);
👍🏻

2021-03-16 10:44 UTC, RomanKashenok commented on lesson13/src/zad32.java
> +        for (String s : str1) {
сделай все это в один поход цикла. Пока у тебя O(n2), а должно быть O(n)

2021-06-15 18:56 UTC, KonstantinLeineveber commented on lesson13/src/zad29.java
> +public class zad29 {
Исправил

2021-06-15 19:31 UTC, KonstantinLeineveber commented on lesson13/src/zad32.java
> +        for (String s : str1) {
Исправил

2021-11-29 13:30 UTC, merged